### ISSUE TITLE
Log files growing indefinitely

### ISSUE THREAD

**Issue by olokos** [antonpup/Aurora#792]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Logs should remain rather small
### Actual behavior:
Explain here what happened instead.
Overnight logs grow to 14GB filling my entire SSD free space
### How often does this problem occur?

This problem occurs... (Fill in here)
Logs just grow gradually into monstrous sizes over time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start aurora
2. Play some game
3. Go afk for 20 hours
4. Enjoy 10GB+ of log files

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
Latest dev release
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
No idea
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Could you give a sample of what is present in the logs?

**Comment by olokos** [comment]
https://i.gyazo.com/89eebe89be358517cc77caf2e6da723f.png
Can't really open this huge files. I'll try to get a smaller log and post it in a few days.

**Comment by SirRenzalot** [comment]
A few days ago my SSD ran out of space (250GB) and after removing unused software I ended up with 13GB free storage. With a bit of research I had found the storage eating monster. I had 156GB aurora logfiles. 

I don´t know what is inside, since the files are way too big to inspect. I am using the 0.6.1 -dev3 version with the voron profile. Maybe an option for no log files could help or it could be induced by the voron profile.

**Comment by diogotr7** [comment]
If you drag those  files into chrome you can open them

**Comment by simon-wh** [comment]
I'm going to add a potentially temporary solution by automatically deleting older log files and potentially checking if the log files are too large.

**Comment by diogotr7** [comment]
Currently my log folder looks like [this](https://i.imgur.com/UcfguVd.png).

The files are mostly filled with a couple dozen of these a second:

`[ERROR] 19:18:04: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role) in C:\Users\diogo\Desktop\l\Aurora\NAudio\NAudio\CoreAudioApi\MMDeviceEnumerator.cs:line 74
   at Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) in C:\Users\diogo\Desktop\l\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 190`

`[ERROR] 01:15:49: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x8889000F): Exception from HRESULT: 0x8889000F
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.WasapiCapture.InitializeCaptureDevice() in C:\Users\diogo\Desktop\l\Aurora\NAudio\NAudio\Wave\WaveInputs\WasapiCapture.cs:line 145
   at NAudio.CoreAudioApi.WasapiCapture.StartRecording() in C:\Users\diogo\Desktop\l\Aurora\NAudio\NAudio\Wave\WaveInputs\WasapiCapture.cs:line 217
   at Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) in C:\Users\diogo\Desktop\l\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 193`

^These two happened in different sessions. I think it might be related to remote desktop, I only noticed this when i started using it.

**Comment by simon-wh** [comment]
@diogotr7 I'm not 100% certain but I think I fixed an issue with those errors appearing in the dev branch. Could you try [this](https://www.dropbox.com/s/09ac7z3208k27bz/v0.6.1-dev3%20log-rl%20test.zip?dl=0)  build and see if you continue to get huge log files? (You can delete those other ones you have which are really big)

**Comment by diogotr7** [comment]
Hey, I just noticed i have 2 ~1.5GB log files on 0.6.1-dev4 with repeating lines of the following:

`[ERROR] 22:46:43: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role) in C:\projects\aurora\NAudio\NAudio\CoreAudioApi\MMDeviceEnumerator.cs:line 74
   at Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 190
[ERROR] 22:46:43: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role) in C:\projects\aurora\NAudio\NAudio\CoreAudioApi\MMDeviceEnumerator.cs:line 74
   at Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 190`


I'm not 100% sure but I think this happens at my home PC whenever i remote desktop into it.

**Comment by simon-wh** [comment]
@diogotr7 Are you sure those are from dev4? Because the lines it mentions do not line up with the lines from dev4.

**Comment by olokos** [comment]
I can confirm that with Aurora v0.6.1-dev4 the issue no longer exists and I can finally use aurora daily, well done guys!

**Comment by ZedeN1** [comment]
issue still present: https://github.com/antonpup/Aurora/issues/1065
